site_name: Dark War Guide
site_url: http://darkwar.oorion.uk
nav:
  - Home: index.md
  - Alliance Duel: versus.md
  - Buildings:
    - Watchtower: buildings/watchtower.md
    - All Camps: buildings/camps.md
    - Research Center: buildings/research-center.md
    - Alliance Hall: buildings/alliance-hall.md
    - Alliance Plaza: buildings/alliance-plaza.md
    - Military Center: buildings/military-center.md
    - City Gate: buildings/city-gate.md
    - Hospital: buildings/hospital.md
  - Updates: notes.md



theme:
  features:
    - navigation.footer
    - navigation.instant
  favicon: /images/logo.jpg
  logo: /images/logo.jpg
  language: en
  name: material
  palette:
     
      # Palette toggle for light mode
      - media: "(prefers-color-scheme: light)"
        scheme: default 
        toggle:
          icon: material/lightbulb-outline
          name: Switch to dark mode

      # Palette toggle for dark mode
      - media: "(prefers-color-scheme: dark)"
        scheme: slate
        toggle:
          icon: material/lightbulb
          name: Switch to system preference
  font:
    text: Space Grotesk

plugins:
  - search

extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discordapp.com/users/401691637434023938
      name: Message me on Discord
  copyright: Copyright &copy
  generator: false
  consent:
    actions:
      - accept
    title: Yummy chocolate cookies!
    description: >- 


      These delicious chocolate chip cookies are used to recognise your
      visits, preferences, bla bla bla bla bla bla bla bla bla bla bla 
      bla bla... you're only here for information on the game. Nothing
      dodgy is going on here, so don't worry. I'm not stealing your data
      or anything else. I don't care. Accept or don't, up to you! It's only
      here for GDPR purposes..
 

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji 
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences
  - footnotes
