backend:
  name: git-gateway
  branch: main

media_folder: "docs/images"
public_folder: "/images"

collections:
  - name: "content"
    label: "Content"
    folder: "docs/"  # Scans ALL Markdown files
    extension: md
    format: frontmatter
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "content", label: "Content", widget: "markdown" }
