backend:
  name: git-gateway
  branch: main  # Your content branch

media_folder: "docs/images"  # Where uploaded images go
public_folder: "/images"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Homepage"
        name: "index"
        file: "docs/index.md"
        fields:
          - { name: title, label: Title, widget: string }
          - { name: content, label: Content, widget: markdown }
