backend:
  name: git-gateway
  branch: main  # Your content branch

media_folder: "docs/images"  # Where uploaded images go
public_folder: "/images"

collections:
  - name: "pages"
    label: "Pages"
    folder: "docs/"  # Scans entire docs directory
    create: true  # Allows new page creation
    slug: "{{slug}}"  # Auto-generates filenames
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "content", label: "Content", widget: "markdown" }
  - name: "config"
    label: "Navigation"
    files:
      - file: "mkdocs.yml"
        label: "Menu Structure"
        fields:
          - { name: "content", label: "YAML Config", widget: "code" }
  
  # Add buildings collection
  - name: "buildings"
    label: "Buildings"
    folder: "docs/buildings"  # Specific subdirectory
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "content", label: "Content", widget: "markdown" }
